// ============================================
// GIMBIE ADVENTIST GENERAL HOSPITAL
// PERMISSIONS - Role-Based Access Control
// ============================================

// ============================================
// ROLE DEFINITIONS
// ============================================

const ROLES = {
  PATIENT: 'patient',
  DOCTOR: 'doctor',
  NURSE: 'nurse',
  RECEPTIONIST: 'receptionist',
  PHARMACIST: 'pharmacist',
  LABORATORY: 'laboratory',
  RADIOLOGIST: 'radiologist',
  FINANCE: 'finance',
  HR: 'hr',
  AMBULANCE: 'ambulance',
  ADMIN: 'admin',
  SUPER_ADMIN: 'super-admin',
};

// ============================================
// PERMISSION DEFINITIONS
// ============================================

const PERMISSIONS = {
  // User Management
  VIEW_USERS: 'view_users',
  CREATE_USER: 'create_user',
  UPDATE_USER: 'update_user',
  DELETE_USER: 'delete_user',
  MANAGE_ROLES: 'manage_roles',
  
  // Patient Management
  VIEW_PATIENTS: 'view_patients',
  VIEW_OWN_PATIENT: 'view_own_patient',
  CREATE_PATIENT: 'create_patient',
  UPDATE_PATIENT: 'update_patient',
  DELETE_PATIENT: 'delete_patient',
  VIEW_PATIENT_RECORDS: 'view_patient_records',
  VIEW_OWN_RECORDS: 'view_own_records',
  
  // Appointment Management
  VIEW_APPOINTMENTS: 'view_appointments',
  VIEW_OWN_APPOINTMENTS: 'view_own_appointments',
  CREATE_APPOINTMENT: 'create_appointment',
  UPDATE_APPOINTMENT: 'update_appointment',
  DELETE_APPOINTMENT: 'delete_appointment',
  CONFIRM_APPOINTMENT: 'confirm_appointment',
  CANCEL_APPOINTMENT: 'cancel_appointment',
  RESCHEDULE_APPOINTMENT: 'reschedule_appointment',
  
  // Prescription Management
  VIEW_PRESCRIPTIONS: 'view_prescriptions',
  CREATE_PRESCRIPTION: 'create_prescription',
  UPDATE_PRESCRIPTION: 'update_prescription',
  VERIFY_PRESCRIPTION: 'verify_prescription',
  DISPENSE_PRESCRIPTION: 'dispense_prescription',
  
  // Medicine Management
  VIEW_MEDICINES: 'view_medicines',
  CREATE_MEDICINE: 'create_medicine',
  UPDATE_MEDICINE: 'update_medicine',
  DELETE_MEDICINE: 'delete_medicine',
  MANAGE_INVENTORY: 'manage_inventory',
  VIEW_INVENTORY: 'view_inventory',
  
  // Lab Management
  VIEW_LAB_TESTS: 'view_lab_tests',
  CREATE_LAB_TEST: 'create_lab_test',
  UPDATE_LAB_TEST: 'update_lab_test',
  PROCESS_LAB_TEST: 'process_lab_test',
  VIEW_LAB_RESULTS: 'view_lab_results',
  
  // Radiology Management
  VIEW_RADIOLOGY_TESTS: 'view_radiology_tests',
  CREATE_RADIOLOGY_TEST: 'create_radiology_test',
  UPDATE_RADIOLOGY_TEST: 'update_radiology_test',
  PERFORM_IMAGING: 'perform_imaging',
  VIEW_IMAGING_RESULTS: 'view_imaging_results',
  
  // Finance Management
  VIEW_INVOICES: 'view_invoices',
  CREATE_INVOICE: 'create_invoice',
  UPDATE_INVOICE: 'update_invoice',
  PROCESS_PAYMENT: 'process_payment',
  VIEW_REVENUE: 'view_revenue',
  VIEW_FINANCIAL_REPORTS: 'view_financial_reports',
  
  // HR Management
  VIEW_STAFF: 'view_staff',
  CREATE_STAFF: 'create_staff',
  UPDATE_STAFF: 'update_staff',
  DELETE_STAFF: 'delete_staff',
  VIEW_ATTENDANCE: 'view_attendance',
  MARK_ATTENDANCE: 'mark_attendance',
  VIEW_PAYROLL: 'view_payroll',
  MANAGE_PAYROLL: 'manage_payroll',
  
  // Ambulance Management
  VIEW_AMBULANCE_REQUESTS: 'view_ambulance_requests',
  CREATE_AMBULANCE_REQUEST: 'create_ambulance_request',
  UPDATE_AMBULANCE_STATUS: 'update_ambulance_status',
  DISPATCH_AMBULANCE: 'dispatch_ambulance',
  VIEW_AMBULANCE_HISTORY: 'view_ambulance_history',
  
  // Admin Management
  VIEW_DASHBOARD: 'view_dashboard',
  VIEW_ANALYTICS: 'view_analytics',
  VIEW_AUDIT_LOGS: 'view_audit_logs',
  MANAGE_SYSTEM_SETTINGS: 'manage_system_settings',
  BACKUP_DATABASE: 'backup_database',
  RESTORE_DATABASE: 'restore_database',
  MANAGE_WEBSITE: 'manage_website',
  MANAGE_NEWS: 'manage_news',
  MANAGE_GALLERY: 'manage_gallery',
  MANAGE_CAREERS: 'manage_careers',
  MANAGE_NOTIFICATIONS: 'manage_notifications',
  
  // Communication
  SEND_MESSAGES: 'send_messages',
  VIEW_MESSAGES: 'view_messages',
  SEND_NOTIFICATIONS: 'send_notifications',
  VIEW_NOTIFICATIONS: 'view_notifications',
  
  // Reports
  VIEW_REPORTS: 'view_reports',
  CREATE_REPORTS: 'create_reports',
  EXPORT_REPORTS: 'export_reports',
  
  // AI Features
  USE_AI_CHAT: 'use_ai_chat',
  USE_AI_SYMPTOM_CHECKER: 'use_ai_symptom_checker',
  USE_AI_SUMMARIZE: 'use_ai_summarize',
};

// ============================================
// ROLE PERMISSION MAPPING
// ============================================

const ROLE_PERMISSIONS = {
  [ROLES.PATIENT]: [
    PERMISSIONS.VIEW_OWN_PATIENT,
    PERMISSIONS.VIEW_OWN_RECORDS,
    PERMISSIONS.VIEW_OWN_APPOINTMENTS,
    PERMISSIONS.CREATE_APPOINTMENT,
    PERMISSIONS.CANCEL_APPOINTMENT,
    PERMISSIONS.VIEW_PRESCRIPTIONS,
    PERMISSIONS.VIEW_LAB_RESULTS,
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.SEND_MESSAGES,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.USE_AI_CHAT,
    PERMISSIONS.USE_AI_SYMPTOM_CHECKER,
  ],
  
  [ROLES.DOCTOR]: [
    PERMISSIONS.VIEW_PATIENTS,
    PERMISSIONS.VIEW_PATIENT_RECORDS,
    PERMISSIONS.VIEW_APPOINTMENTS,
    PERMISSIONS.VIEW_OWN_APPOINTMENTS,
    PERMISSIONS.UPDATE_APPOINTMENT,
    PERMISSIONS.CONFIRM_APPOINTMENT,
    PERMISSIONS.CANCEL_APPOINTMENT,
    PERMISSIONS.RESCHEDULE_APPOINTMENT,
    PERMISSIONS.CREATE_PRESCRIPTION,
    PERMISSIONS.VIEW_PRESCRIPTIONS,
    PERMISSIONS.CREATE_LAB_TEST,
    PERMISSIONS.VIEW_LAB_RESULTS,
    PERMISSIONS.CREATE_RADIOLOGY_TEST,
    PERMISSIONS.VIEW_IMAGING_RESULTS,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.SEND_MESSAGES,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.USE_AI_CHAT,
    PERMISSIONS.USE_AI_SUMMARIZE,
  ],
  
  [ROLES.NURSE]: [
    PERMISSIONS.VIEW_PATIENTS,
    PERMISSIONS.VIEW_PATIENT_RECORDS,
    PERMISSIONS.VIEW_APPOINTMENTS,
    PERMISSIONS.VIEW_MEDICINES,
    PERMISSIONS.VIEW_LAB_RESULTS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.SEND_MESSAGES,
    PERMISSIONS.MARK_ATTENDANCE,
    PERMISSIONS.VIEW_ATTENDANCE,
  ],
  
  [ROLES.RECEPTIONIST]: [
    PERMISSIONS.CREATE_PATIENT,
    PERMISSIONS.VIEW_PATIENTS,
    PERMISSIONS.VIEW_OWN_PATIENT,
    PERMISSIONS.UPDATE_PATIENT,
    PERMISSIONS.CREATE_APPOINTMENT,
    PERMISSIONS.VIEW_APPOINTMENTS,
    PERMISSIONS.UPDATE_APPOINTMENT,
    PERMISSIONS.CONFIRM_APPOINTMENT,
    PERMISSIONS.CANCEL_APPOINTMENT,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.SEND_MESSAGES,
    PERMISSIONS.VIEW_NOTIFICATIONS,
  ],
  
  [ROLES.PHARMACIST]: [
    PERMISSIONS.VIEW_PRESCRIPTIONS,
    PERMISSIONS.VERIFY_PRESCRIPTION,
    PERMISSIONS.DISPENSE_PRESCRIPTION,
    PERMISSIONS.VIEW_MEDICINES,
    PERMISSIONS.CREATE_MEDICINE,
    PERMISSIONS.UPDATE_MEDICINE,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.CREATE_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
  ],
  
  [ROLES.LABORATORY]: [
    PERMISSIONS.VIEW_LAB_TESTS,
    PERMISSIONS.UPDATE_LAB_TEST,
    PERMISSIONS.PROCESS_LAB_TEST,
    PERMISSIONS.VIEW_LAB_RESULTS,
    PERMISSIONS.VIEW_PATIENTS,
    PERMISSIONS.VIEW_APPOINTMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.CREATE_REPORTS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
  ],
  
  [ROLES.RADIOLOGIST]: [
    PERMISSIONS.VIEW_RADIOLOGY_TESTS,
    PERMISSIONS.UPDATE_RADIOLOGY_TEST,
    PERMISSIONS.PERFORM_IMAGING,
    PERMISSIONS.VIEW_IMAGING_RESULTS,
    PERMISSIONS.VIEW_PATIENTS,
    PERMISSIONS.VIEW_APPOINTMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.CREATE_REPORTS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
  ],
  
  [ROLES.FINANCE]: [
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.CREATE_INVOICE,
    PERMISSIONS.UPDATE_INVOICE,
    PERMISSIONS.PROCESS_PAYMENT,
    PERMISSIONS.VIEW_REVENUE,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.CREATE_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
  ],
  
  [ROLES.HR]: [
    PERMISSIONS.VIEW_STAFF,
    PERMISSIONS.CREATE_STAFF,
    PERMISSIONS.UPDATE_STAFF,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.MARK_ATTENDANCE,
    PERMISSIONS.VIEW_PAYROLL,
    PERMISSIONS.MANAGE_PAYROLL,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.CREATE_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
  ],
  
  [ROLES.AMBULANCE]: [
    PERMISSIONS.VIEW_AMBULANCE_REQUESTS,
    PERMISSIONS.CREATE_AMBULANCE_REQUEST,
    PERMISSIONS.UPDATE_AMBULANCE_STATUS,
    PERMISSIONS.DISPATCH_AMBULANCE,
    PERMISSIONS.VIEW_AMBULANCE_HISTORY,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_REPORTS,
  ],
  
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.DELETE_USER,
    PERMISSIONS.VIEW_PATIENTS,
    PERMISSIONS.CREATE_PATIENT,
    PERMISSIONS.UPDATE_PATIENT,
    PERMISSIONS.DELETE_PATIENT,
    PERMISSIONS.VIEW_APPOINTMENTS,
    PERMISSIONS.CREATE_APPOINTMENT,
    PERMISSIONS.UPDATE_APPOINTMENT,
    PERMISSIONS.DELETE_APPOINTMENT,
    PERMISSIONS.CONFIRM_APPOINTMENT,
    PERMISSIONS.VIEW_PRESCRIPTIONS,
    PERMISSIONS.VIEW_MEDICINES,
    PERMISSIONS.CREATE_MEDICINE,
    PERMISSIONS.UPDATE_MEDICINE,
    PERMISSIONS.DELETE_MEDICINE,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.VIEW_LAB_TESTS,
    PERMISSIONS.VIEW_RADIOLOGY_TESTS,
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.CREATE_INVOICE,
    PERMISSIONS.PROCESS_PAYMENT,
    PERMISSIONS.VIEW_REVENUE,
    PERMISSIONS.VIEW_STAFF,
    PERMISSIONS.CREATE_STAFF,
    PERMISSIONS.UPDATE_STAFF,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.MARK_ATTENDANCE,
    PERMISSIONS.VIEW_PAYROLL,
    PERMISSIONS.VIEW_AMBULANCE_REQUESTS,
    PERMISSIONS.DISPATCH_AMBULANCE,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_SYSTEM_SETTINGS,
    PERMISSIONS.BACKUP_DATABASE,
    PERMISSIONS.MANAGE_WEBSITE,
    PERMISSIONS.MANAGE_NEWS,
    PERMISSIONS.MANAGE_GALLERY,
    PERMISSIONS.MANAGE_CAREERS,
    PERMISSIONS.MANAGE_NOTIFICATIONS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.CREATE_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.SEND_NOTIFICATIONS,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.SEND_MESSAGES,
    PERMISSIONS.USE_AI_CHAT,
    PERMISSIONS.USE_AI_SUMMARIZE,
  ],
  
  [ROLES.SUPER_ADMIN]: [
    // All permissions
    ...Object.values(PERMISSIONS),
  ],
};

// ============================================
// HELPER FUNCTIONS
// ============================================

exports.hasPermission = (role, permission) => {
  const permissions = ROLE_PERMISSIONS[role] || [];
  return permissions.includes(permission);
};

exports.getRolePermissions = (role) => {
  return ROLE_PERMISSIONS[role] || [];
};

exports.getAllRoles = () => {
  return Object.values(ROLES);
};

exports.getAllPermissions = () => {
  return Object.values(PERMISSIONS);
};

// ============================================
// EXPORT
// ============================================

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission: exports.hasPermission,
  getRolePermissions: exports.getRolePermissions,
  getAllRoles: exports.getAllRoles,
  getAllPermissions: exports.getAllPermissions,
};
