const nodemailer = require('nodemailer');
const PDFDocument = require('pdfkit');
const QRCode = require('qrcode');
const fs = require('fs');
const path = require('path');
const config = require('./config');

// Email Service
class EmailService {
  constructor() {
    this.transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: config.emailUser,
        pass: config.emailPass
      }
    });
  }

  async sendEmail(to, subject, html, text = '') {
    try {
      const mailOptions = {
        from: `${config.hospitalName} <${config.emailUser}>`,
        to,
        subject,
        html,
        text
      };

      const info = await this.transporter.sendMail(mailOptions);
      console.log('Email sent:', info.messageId);
      return info;
    } catch (error) {
      console.error('Email error:', error);
      throw error;
    }
  }

  async sendAppointmentConfirmation(email, details) {
    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #1a3a5c;">${config.hospitalName}</h1>
        <h2>Appointment Confirmation</h2>
        <p>Dear ${details.patientName},</p>
        <p>Your appointment has been confirmed:</p>
        <ul>
          <li><strong>Doctor:</strong> Dr. ${details.doctorName}</li>
          <li><strong>Date:</strong> ${details.date}</li>
          <li><strong>Time:</strong> ${details.time}</li>
          <li><strong>Reason:</strong> ${details.reason || 'General consultation'}</li>
        </ul>
        <p><strong>Please arrive 15 minutes before your appointment.</strong></p>
        <p>Thank you for choosing ${config.hospitalName}.</p>
        <hr />
        <p style="color: #666; font-size: 12px;">
          ${config.hospitalName}<br />
          Phone: ${config.hospitalPhone}<br />
          Email: ${config.hospitalEmail}<br />
          Address: ${config.hospitalAddress}
        </p>
      </div>
    `;
    return this.sendEmail(email, 'Appointment Confirmation', html);
  }

  async sendLabResult(email, patientName, testName, result) {
    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #1a3a5c;">${config.hospitalName}</h1>
        <h2>Laboratory Test Result</h2>
        <p>Dear ${patientName},</p>
        <p>Your laboratory test result is now available:</p>
        <div style="background: #f5f5f5; padding: 15px; border-radius: 8px;">
          <p><strong>Test:</strong> ${testName}</p>
          <p><strong>Status:</strong> Completed</p>
          <p><strong>Result:</strong> ${result.interpretation || 'Please log in to view details'}</p>
        </div>
        <p>Please log in to your patient portal to view the complete report.</p>
        <p>Thank you for choosing ${config.hospitalName}.</p>
      </div>
    `;
    return this.sendEmail(email, 'Lab Result Available', html);
  }
}

// PDF Generation Service
class PDFService {
  constructor() {
    this.hospitalName = config.hospitalName;
    this.hospitalAddress = config.hospitalAddress;
    this.hospitalPhone = config.hospitalPhone;
    this.hospitalEmail = config.hospitalEmail;
  }

  generateHeader(doc) {
    doc.fontSize(14)
      .font('Helvetica-Bold')
      .text(this.hospitalName, { align: 'center' });
    doc.fontSize(10)
      .font('Helvetica')
      .text(this.hospitalAddress, { align: 'center' })
      .text(`Tel: ${this.hospitalPhone} | Email: ${this.hospitalEmail}`, { align: 'center' });
    doc.moveDown();
  }

  generateFooter(doc) {
    doc.fontSize(8)
      .font('Helvetica')
      .text('Generated by Gimbie Adventist Hospital Management System', {
        align: 'center',
        color: '#666'
      });
  }

  async generatePatientCard(patient) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ size: 'A6', margin: 20 });
        const buffers = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
          const pdfData = Buffer.concat(buffers);
          resolve(pdfData);
        });

        this.generateHeader(doc);
        doc.fontSize(12)
          .font('Helvetica-Bold')
          .text('PATIENT ID CARD', { align: 'center' });
        doc.moveDown();

        doc.fontSize(10)
          .font('Helvetica')
          .text(`Patient ID: ${patient.patientId}`)
          .text(`Name: ${patient.firstName} ${patient.lastName}`)
          .text(`Date of Birth: ${new Date(patient.dateOfBirth).toLocaleDateString()}`)
          .text(`Gender: ${patient.gender}`)
          .text(`Blood Group: ${patient.bloodGroup || 'N/A'}`)
          .text(`Phone: ${patient.phone}`)
          .text(`Emergency Contact: ${patient.emergencyContact?.name || 'N/A'}`)
          .text(`Registered: ${new Date(patient.createdAt).toLocaleDateString()}`);

        // Add QR Code
        if (patient.qrCode) {
          const qrImage = patient.qrCode.replace(/^data:image\/png;base64,/, '');
          const qrBuffer = Buffer.from(qrImage, 'base64');
          doc.image(qrBuffer, 150, 350, { width: 80 });
        }

        this.generateFooter(doc);
        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  async generateConsultationSheet(consultation) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ size: 'A4', margin: 40 });
        const buffers = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
          const pdfData = Buffer.concat(buffers);
          resolve(pdfData);
        });

        this.generateHeader(doc);
        doc.fontSize(14)
          .font('Helvetica-Bold')
          .text('CONSULTATION SHEET', { align: 'center' });
        doc.moveDown();

        const patient = consultation.patient;
        const doctor = consultation.doctor;

        doc.fontSize(10)
          .font('Helvetica')
          .text(`Patient ID: ${patient.patientId}`)
          .text(`Patient Name: ${patient.firstName} ${patient.lastName}`)
          .text(`Date of Birth: ${new Date(patient.dateOfBirth).toLocaleDateString()}`)
          .text(`Phone: ${patient.phone}`)
          .text(`Date: ${new Date(consultation.date).toLocaleString()}`)
          .text(`Doctor: Dr. ${doctor.firstName} ${doctor.lastName} (${doctor.specialization})`)
          .moveDown();

        doc.font('Helvetica-Bold')
          .text('Symptoms:');
        doc.font('Helvetica')
          .text(consultation.symptoms?.join(', ') || 'None')
          .moveDown();

        doc.font('Helvetica-Bold')
          .text('Vital Signs:');
        doc.font('Helvetica');
        if (consultation.vitalSigns) {
          const vs = consultation.vitalSigns;
          doc.text(`Blood Pressure: ${vs.bloodPressure || 'N/A'}`)
            .text(`Heart Rate: ${vs.heartRate || 'N/A'} bpm`)
            .text(`Temperature: ${vs.temperature || 'N/A'} °C`)
            .text(`Weight: ${vs.weight || 'N/A'} kg`)
            .text(`BMI: ${vs.bmi || 'N/A'}`);
        }
        doc.moveDown();

        doc.font('Helvetica-Bold')
          .text('Diagnosis:');
        doc.font('Helvetica')
          .text(consultation.diagnosis || 'N/A')
          .moveDown();

        doc.font('Helvetica-Bold')
          .text('Treatment Plan:');
        doc.font('Helvetica')
          .text(consultation.treatmentPlan || 'N/A')
          .moveDown();

        doc.font('Helvetica-Bold')
          .text('Notes:');
        doc.font('Helvetica')
          .text(consultation.notes || 'N/A')
          .moveDown();

        if (consultation.followUpDate) {
          doc.text(`Follow-up Date: ${new Date(consultation.followUpDate).toLocaleDateString()}`);
        }

        doc.moveDown();
        doc.text('Doctor Signature: ____________________', { align: 'right' });
        doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'right' });

        // Add QR Code
        if (consultation.qrCode) {
          const qrImage = consultation.qrCode.replace(/^data:image\/png;base64,/, '');
          const qrBuffer = Buffer.from(qrImage, 'base64');
          doc.image(qrBuffer, 450, 700, { width: 60 });
        }

        this.generateFooter(doc);
        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  async generatePrescriptionSheet(prescription) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ size: 'A4', margin: 40 });
        const buffers = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
          const pdfData = Buffer.concat(buffers);
          resolve(pdfData);
        });

        this.generateHeader(doc);
        doc.fontSize(14)
          .font('Helvetica-Bold')
          .text('PRESCRIPTION', { align: 'center' });
        doc.moveDown();

        const patient = prescription.patient;
        const doctor = prescription.doctor;

        doc.fontSize(10)
          .font('Helvetica')
          .text(`Patient ID: ${patient.patientId}`)
          .text(`Patient Name: ${patient.firstName} ${patient.lastName}`)
          .text(`Date of Birth: ${new Date(patient.dateOfBirth).toLocaleDateString()}`)
          .text(`Date: ${new Date(prescription.date).toLocaleString()}`)
          .text(`Doctor: Dr. ${doctor.firstName} ${doctor.lastName} (${doctor.specialization})`)
          .moveDown();

        if (prescription.diagnosis) {
          doc.font('Helvetica-Bold').text('Diagnosis:');
          doc.font('Helvetica').text(prescription.diagnosis).moveDown();
        }

        doc.font('Helvetica-Bold')
          .text('Medicines:')
          .moveDown();

        const tableTop = doc.y;
        const tableHeaders = ['Medicine', 'Dosage', 'Frequency', 'Duration', 'Instructions'];
        const colWidths = [120, 80, 80, 80, 100];

        // Headers
        doc.font('Helvetica-Bold');
        let x = 50;
        tableHeaders.forEach((header, i) => {
          doc.text(header, x, tableTop, { width: colWidths[i], align: 'left' });
          x += colWidths[i];
        });

        // Data rows
        doc.font('Helvetica');
        let y = tableTop + 20;
        prescription.medicines.forEach((medicine) => {
          x = 50;
          doc.text(medicine.name, x, y, { width: colWidths[0] });
          x += colWidths[0];
          doc.text(medicine.dosage, x, y, { width: colWidths[1] });
          x += colWidths[1];
          doc.text(medicine.frequency, x, y, { width: colWidths[2] });
          x += colWidths[2];
          doc.text(medicine.duration, x, y, { width: colWidths[3] });
          x += colWidths[3];
          doc.text(medicine.instructions || '', x, y, { width: colWidths[4] });
          y += 20;
        });

        doc.moveDown(2);
        if (prescription.notes) {
          doc.font('Helvetica-Bold').text('Notes:');
          doc.font('Helvetica').text(prescription.notes);
        }

        doc.moveDown();
        doc.text('Doctor Signature: ____________________', { align: 'right' });
        doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'right' });

        // Add QR Code
        if (prescription.qrCode) {
          const qrImage = prescription.qrCode.replace(/^data:image\/png;base64,/, '');
          const qrBuffer = Buffer.from(qrImage, 'base64');
          doc.image(qrBuffer, 450, 700, { width: 60 });
        }

        this.generateFooter(doc);
        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  async generateInvoice(bill) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ size: 'A4', margin: 40 });
        const buffers = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
          const pdfData = Buffer.concat(buffers);
          resolve(pdfData);
        });

        this.generateHeader(doc);
        doc.fontSize(16)
          .font('Helvetica-Bold')
          .text('INVOICE', { align: 'center' });
        doc.moveDown();

        const patient = bill.patient;

        doc.fontSize(10)
          .font('Helvetica')
          .text(`Invoice Number: ${bill.billNumber}`)
          .text(`Date: ${new Date(bill.createdAt).toLocaleString()}`)
          .text(`Patient ID: ${patient.patientId}`)
          .text(`Patient Name: ${patient.firstName} ${patient.lastName}`)
          .text(`Phone: ${patient.phone}`)
          .moveDown();

        // Items table
        doc.font('Helvetica-Bold')
          .text('Items:')
          .moveDown();

        const tableTop = doc.y;
        const tableHeaders = ['#', 'Description', 'Qty', 'Unit Price', 'Total'];
        const colWidths = [30, 280, 50, 80, 80];

        let x = 50;
        tableHeaders.forEach((header, i) => {
          doc.text(header, x, tableTop, { width: colWidths[i], align: 'left' });
          x += colWidths[i];
        });

        doc.font('Helvetica');
        let y = tableTop + 20;
        bill.items.forEach((item, index) => {
          x = 50;
          doc.text(index + 1, x, y, { width: colWidths[0] });
          x += colWidths[0];
          doc.text(item.description, x, y, { width: colWidths[1] });
          x += colWidths[1];
          doc.text(item.quantity, x, y, { width: colWidths[2] });
          x += colWidths[2];
          doc.text(`$${item.unitPrice.toFixed(2)}`, x, y, { width: colWidths[3] });
          x += colWidths[3];
          doc.text(`$${item.total.toFixed(2)}`, x, y, { width: colWidths[4] });
          y += 20;
        });

        doc.moveDown(2);
        doc.font('Helvetica-Bold')
          .text(`Subtotal: $${bill.subtotal.toFixed(2)}`, { align: 'right' });

        if (bill.discount > 0) {
          const discountText = bill.discountType === 'percentage' 
            ? `${bill.discount}%` 
            : `$${bill.discount.toFixed(2)}`;
          doc.text(`Discount: ${discountText}`, { align: 'right' });
        }

        if (bill.tax > 0) {
          doc.text(`Tax (${bill.tax}%): $${(bill.subtotal * bill.tax / 100).toFixed(2)}`, { align: 'right' });
        }

        doc.fontSize(14)
          .font('Helvetica-Bold')
          .text(`Total Amount: $${bill.totalAmount.toFixed(2)}`, { align: 'right' });
        doc.fontSize(10)
          .font('Helvetica')
          .text(`Payment Status: ${bill.paymentStatus.toUpperCase()}`, { align: 'right' });

        if (bill.amountPaid > 0) {
          doc.text(`Amount Paid: $${bill.amountPaid.toFixed(2)}`, { align: 'right' });
          doc.text(`Balance: $${bill.balance.toFixed(2)}`, { align: 'right' });
        }

        this.generateFooter(doc);
        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  async generateLabRequest(request) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ size: 'A4', margin: 40 });
        const buffers = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
          const pdfData = Buffer.concat(buffers);
          resolve(pdfData);
        });

        this.generateHeader(doc);
        doc.fontSize(14)
          .font('Helvetica-Bold')
          .text('LABORATORY REQUEST FORM', { align: 'center' });
        doc.moveDown();

        const patient = request.patient;
        const doctor = request.doctor;

        doc.fontSize(10)
          .font('Helvetica')
          .text(`Patient ID: ${patient.patientId}`)
          .text(`Patient Name: ${patient.firstName} ${patient.lastName}`)
          .text(`Date of Birth: ${new Date(patient.dateOfBirth).toLocaleDateString()}`)
          .text(`Phone: ${patient.phone}`)
          .text(`Request Date: ${new Date(request.requestDate).toLocaleString()}`)
          .text(`Doctor: Dr. ${doctor.firstName} ${doctor.lastName}`)
          .text(`Priority: ${request.priority?.toUpperCase() || 'ROUTINE'}`)
          .moveDown();

        doc.font('Helvetica-Bold')
          .text('Requested Tests:')
          .moveDown();

        request.tests.forEach((test, index) => {
          doc.font('Helvetica')
            .text(`${index + 1}. ${test.name}${test.category ? ` (${test.category})` : ''}`);
          if (test.notes) {
            doc.text(`   Notes: ${test.notes}`);
          }
        });

        doc.moveDown();
        if (request.clinicalNotes) {
          doc.font('Helvetica-Bold')
            .text('Clinical Notes:');
          doc.font('Helvetica')
            .text(request.clinicalNotes);
        }

        doc.moveDown();
        doc.text('Doctor Signature: ____________________', { align: 'right' });
        doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'right' });

        // Add QR Code
        if (request.qrCode) {
          const qrImage = request.qrCode.replace(/^data:image\/png;base64,/, '');
          const qrBuffer = Buffer.from(qrImage, 'base64');
          doc.image(qrBuffer, 450, 700, { width: 60 });
        }

        this.generateFooter(doc);
        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }
}

// File Service
class FileService {
  constructor() {
    this.uploadPath = config.uploadPath;
  }

  async saveFile(file, folder) {
    const path = require('path');
    const fs = require('fs');
    const { v4: uuidv4 } = require('uuid');

    const ext = path.extname(file.name);
    const filename = `${uuidv4()}${ext}`;
    const uploadDir = path.join(__dirname, 'uploads', folder);
    
    if (!fs.existsSync(uploadDir)) {
      fs.mkdirSync(uploadDir, { recursive: true });
    }

    const filePath = path.join(uploadDir, filename);
    await file.mv(filePath);

    return `/uploads/${folder}/${filename}`;
  }

  async deleteFile(filePath) {
    const fs = require('fs');
    const path = require('path');
    const fullPath = path.join(__dirname, filePath);
    
    if (fs.existsSync(fullPath)) {
      fs.unlinkSync(fullPath);
      return true;
    }
    return false;
  }
}

module.exports = {
  EmailService: new EmailService(),
  PDFService: new PDFService(),
  FileService: new FileService()
};
